### ISSUE TITLE
Display of GUI of dnfdragora is highly unlogical due to layout issue related to libyui !

### ISSUE THREAD

**Issue by Nokia808** [libyui/libyui-qt#70]
Hi. I opened this issue in dnfdragora page at:
https://github.com/manatools/dnfdragora/issues/62

Developer ask me to move discussion about point 1 here. 
I'm not sure whether title should be modified here or not ? If need modification, then modify it as it need.

Here is subject:
Hi. Currently, dnfdragora on Fedora has unlogical GUI due to most importantly, size of individual columns are very wide make user unable to see enough amount of descriptions & data ! User need to scroll horizontally for that !

**Comment by shundhammer** [comment]
I found this while cleaning up old issues.

Unfortunately, there is no screenshot (neither here nor in that other issue), so I am not 100% sure if this applies here.

But this used to be an FAQ; back years ago I had even started an FAQ section with this as one of the most prominent FAQs:

_**Q: Why does libyui have captions above a widget and not to its left?**_

_**A:** To avoid large chunks of empty space for widgets of different height. If you have only one-line widgets like input fields and combo boxes, this is easy; but as soon as you have any multi-line widgets like a selection box (the one with multiple items to select from in a multi-line widget) or a multi-line input widget or a table, this results in a lot of empty space on the left.

But libyui was primarily used for the SUSE Linux installer where screen space tends to be scarce because of limited screen resolutions during installation, so wasting screen space was a poor option. This is why the captions are above, not to the left of input widgets; that way, there is no excessive empty grey space._

I am pretty sure that this applies here as well, and that dnfdragora program just tried to cheat the mechanics and the intent of libyui by artificially trying to put the widget captions to the left side.

Simple solution: Don't do that in that program. Use the UI the way it was intended to be used.

**Comment by Nokia808** [comment]
Hi. I'm sorry for delay. These are screenshots attached here. Please see them as their number sequence.
![1](https://user-images.githubusercontent.com/25375330/54852896-22b53200-4ce6-11e9-84dd-434b804db5fb.png)
![2](https://user-images.githubusercontent.com/25375330/54852897-22b53200-4ce6-11e9-88fc-8d6fd41d396b.png)
![3](https://user-images.githubusercontent.com/25375330/54852899-22b53200-4ce6-11e9-812c-a9f061e1742b.png)
![4](https://user-images.githubusercontent.com/25375330/54852900-22b53200-4ce6-11e9-9739-8aeee1889bd9.png)
![5](https://user-images.githubusercontent.com/25375330/54852901-234dc880-4ce6-11e9-8e10-f015c3e8935c.png)
![6](https://user-images.githubusercontent.com/25375330/54852902-234dc880-4ce6-11e9-96ea-c8f18560986d.png)

**Comment by kn00tcn** [comment]
the problem is that columns automatically expand based on the longest text in any row, so if there is a package with a very long name, the name column gets very long

i dont know if libyui or dnfdragora are to override this, having say a max column size by default & then show ... on long text entries

**Comment by anaselli** [comment]
[test-Ytable.cc.txt](https://github.com/libyui/libyui-qt/files/2999193/test-Ytable.cc.txt)
Above example, adapted from libyui one, gives the following output:

![Columns into YTable from libyui example](https://user-images.githubusercontent.com/1303486/54864428-8deb1c80-4d57-11e9-9afa-3c5bd3ce5f89.png)

**Comment by shundhammer** [comment]
I just changed the subject accordingly. The old one was completely misleading.

There is nothing _unlogical_. You have a personal preference that does not match what the widget does by itself.

Yes, that YTable widget makes sure that no texts are cut off in the column content. That's not "unlogical"; that is the natural strategy how those things work.

The widget can scroll in both dimensions. If texts in some columns are very much wider than the others, that means that the column becomes wide enough so even the longest text fits in, and the user has to scroll more.

Another approach would be to let the application explicitly specify a width for each column, or, alternatively, a maximum width. How wide that would be would be up to the application to find out (mostly by trial and error from the application developers' side); there is no way for the library to find out.

When you use the underlying Qt libraries, of course you can do all that on a very fine-grain level. But still it comes down to trial and error and some rule-of-thumb what looks acceptable (which is a mater of personal taste, of course).

With a generic UI library like libyui that would make the API for that part really awkward, and still the vast majority of application developers would get that wrong (don't get me started about that; I've seen that happening in 25+ years as a "tool maker" trying to adapt powerful, yet complex GUI libaries like Qt and OSF/Motif to what is realistic to handle for the average application developer).

There are things like font metrics that come into play, internationalization issues (text lengths in different languages etc.), and the main feature of libyui would go down the drain quickly: Being transparent towards the target system, GUI (Qt, formerly also Gtk) vs. TUI (text mode / NCurses).

Bottom line: No. There is no reasonable way to do that given the constraints that a library like libyui has. If you need that level of micromanagement, you'll have to go deep down into the gory details of Qt itself, and even then it will not always work reliably.

This is also one of the reasons why we have the YQPackageSelector widget for package management which has similar requirements: This allowed us to take much finer control of those details.

dnfdagora might go down a similar route if you can identify what exact requirements you have and where to draw the line with a high-level widget like that. It doesn't have to be the entire dialog content (which is what we did with the YQPackageSelector widget); maybe just abstracting one of the tables would be enough.

It could use the plug-in mechanism that is already in place for libyui-qt-pkg.

**Comment by anaselli** [comment]
I understand such a property is very hard to implement in ncurses, but i don't think it's a personal preference, if you open the QT designer and create a widget the property column size is often with less room than the property content, and you can resize it to read it better. And most application just show columns according to windows size e.g. minimum possible or larger if in full screen. That's my opinion of course...

**Comment by kn00tcn** [comment]
it's indeed common that many other apps simply use ... on long cells so that all columns are visible at once, they even ... column headings if needed, but i think that's too much

so what i would do is have minimum column widths be based on the column headings, resulting in a scrollbar IF needed to fit headings

then as the window enlarges horizontally, expand columns with ... cells

then comes a possible personal preference, for large windows where all content can fit, either have all columns the min width needed to fit the longest cells of each so that everything is left aligned with empty space on the right, or continue scaling all columns so that every cell/column gets some empty space to fill the entire 'table' to full width

(note: i'm only familiar with front-end web development, so i dont know how OS gui frameworks work, how many different widgets can achieve a similar result to the end user, etc)

**Comment by shundhammer** [comment]
The column headings are by far the least desirable measure for the width of each column; that is my experience from 22 years of programming with Qt (since 1997 or so).

There is just no easy way to get this right, in particular if we have to take both Qt and NCurses into account. Add to that different window sizes (even if you use fullscreen there are a gazillion different screen resolutions to take care of!) and resize behaviour, and you end up with a royal mess pretty quickly.  It gets worse if a dialog has multiple tables side by side.

I repeat: If you want that kind of micromanagement, you'll have to do it on a much lower level. There is no reasonable way to do it on the level of libyui.

**Comment by shundhammer** [comment]
Since this application (as far as I can tell from the screenshots) literally reimplements the YPackageSelector widget, why not do it the proper way and _implement_ those widgets? 

You are even lucky to have the YaST/SUSE YQPackageSelector as an example how to do that. You could copy the parts that you want, carve out the libzypp calls and replace them with whatever calls you need to use.

There is a reason why we made that part separate back then: We found in previous versions of YaST that a UI framework that targets simplicity over features like libyui is simply too limiting if you have to cram all that complexity into this limited screen space.

What you intend to do here is to squarify the circle, and you just found out that the octagon you got (which is already a step up from the previous hexagon) still has too many corners for comfort. :smiley:

**Comment by anaselli** [comment]
iirc YQPackageSelector is for QT. And libyui is not QT only. Said that always iirc i discarded it because it was for suse, no urpmi, yum, and now not dnf.  And i found tons of bug before having an usable libyui for implementing an application that could be used for ncurses, QT and GTK (yes GTK too). Most i fixed other i workarounded. honestly speaking i cannot remember now why i discarded plugins, probably because they didn't do what i expected, or maybe for the lack of documentation and the try and error method was not so of help... 
I wish you understand that this project is a great idea, but without support (even for managing merge request) is so frustrating...

**Comment by anaselli** [comment]
And by the way what does it happen if i add a cell content longer than first insertion? Look at Notes column....
![YTable adding a later long cell content](https://user-images.githubusercontent.com/1303486/54959685-2fda5700-4f5a-11e9-8405-688fb5204f1f.png)

**Comment by anaselli** [comment]
Sorry i used my implementation of YCBTable, to avoid any doubts here you have original YTable, added into Left column
![YTable adding a later long cell content](https://user-images.githubusercontent.com/1303486/54959875-d9214d00-4f5a-11e9-8bd1-facf72fc71be.png)

**Comment by anaselli** [comment]
while ncurses still work enlarging columns... So why don't allow the same behaviour on the first insertion, maybe adding a flag for it?
![YTable adding a later long cell content ncurses](https://user-images.githubusercontent.com/1303486/54959998-4e8d1d80-4f5b-11e9-9461-483c05de1cde.png)

**Comment by kn00tcn** [comment]
ooh, forgot to mention OP & I are using gtk instead of qt

**Comment by anaselli** [comment]
> ooh, forgot to mention OP & I are using gtk instead of qt (maybe it was obvious from screenshots)
> 
> EDIT: dnfdragora would be adding yes, since it's filling in the rows over time

Not to mantion we are developing a set of tools not only package manager... [manatools](https://github.com/manatools/)

**Comment by shundhammer** [comment]
> iirc YQPackageSelector is for QT. 

It's **Qt**, not QT. QT is Apple QuickTime. The Trolls keep insisting on that.
SCNR

You do know that there is also an NCurses counterpart, written entirely in C++ using libyui?
Of course, with that you don't get the fine control that Qt has to offer.

As for Gtk: Since the original author of libyui-gtk and his mentor left the project, this had been abandoned for a long time, and we no longer support it.

So this is not a libyui problem after all, but a problem of libyui-gtk?

**Comment by shundhammer** [comment]
> > EDIT: dnfdragora would be adding yes, since it's filling in the rows over time
> 
> Not to mention we are developing a set of tools not only package manager... [manatools](https://github.com/manatools/)

Very much like YaST.

I didn't imply to write _everything_ in C++ with Qt as a specialized widget. But the one thing that you obviously use is the _PackageSelector_ widget.

I was just making a suggestion. It's your choice to heed or to ignore such advice.

But I know for certain that we are not going to introduce that level of micromanagement into libyui. You will either have to live with the available tools or create your own dedicated solution for your specific requirements.

This is not a fault of libyui or of its design; it's unrealistic expectations to what a toolset like libyui can and wants to offer.

**Comment by jreidinger** [comment]
Just note libyui-gtk is not supported by YaST team from SUSE, but of course it is still used and maintained by community contributors that are still using it.

**Comment by anaselli** [comment]
@jreidinger who has to note? I think you know how much I helped this project. And for my pow libyui is all  e.g. libyui, libyui-qt and libyui-gtk. If one of them has problems the whole project has. Don't get me wrong I'm no ignoring your advices, 'm just trying to avoid throwing away all, and if that is the solution I probably must change framework loosing what good it is in, e.g. libyui.
YAST (don't know which are really capital letters) is not the solution... don't know yast, but some manatools were able to run into mageia,  suse, fedora and debian.
